_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/hw0/handout/txt_classifier.py
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 40
                - 41
                - 55
            "2":
                - 1
                - 40
                - 41
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.9.6
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
